export const staticSearchIndex = [
  { title: "About Us", href: "/about" },
  { title: "Corporate Office", href: "/corporate-office" },
  { title: "Leadership", href: "/leadership" },
  { title: "Business Incubation Programme", href: "/business-incubation-programme" },
  { title: "Entrepreneurship Training", href: "/entrepreneurship-training" },
  { title: "Mentorship Programme", href: "/mentorship-programme" },
  { title: "Enterprise & Skills Development", href: "/enterprise-skills-development" },
  { title: "Apply for Incubation", href: "/apply" },
  { title: "Help Center", href: "/help-center" },
  { title: "Contact IT Support", href: "/help-center#it-support" },
  { title: "Contact Us", href: "/contact" },
  { title: "National Grant Structure", href: "/national-grant-structure" },
  { title: "Corporate Procurement Connections", href: "/corporate-procurement-connections" },
  { title: "Tenders & Public Sector Panels", href: "/tenders-public-sector-panels" },
  { title: "Privacy Policy", href: "/privacy-policy" },
  { title: "Terms of Service", href: "/terms-of-service" },
  { title: "Cookie Policy", href: "/cookie-policy" },
];